---
apiVersion: v1
kind: Namespace
metadata:
  name: sumologic
---
apiVersion: v1
data:
  config.yaml: |2

    receivers:
      raw_k8s_events:
    extensions:
      health_check: {}
      file_storage:
        directory: /var/lib/storage/otc
        timeout: 10s
      pprof: {}
    exporters:
      logging:
      sumologic:
        log_format: json
        json_logs:
          add_timestamp: true
          timestamp_key: timestamp
        endpoint: ${SUMO_ENDPOINT_DEFAULT_EVENT_SOURCE}
        source_name: "%{_sourceName}"
        source_category: "%{_sourceCategory}"
        sending_queue:
          enabled: true

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 80
        spike_limit_percentage: 10
      batch:
        send_batch_size: 1024
        send_batch_max_size: 2_048
        timeout: 1s
      source:
        collector: 'kubernetes'
        source_name: "events"
        source_category: "kubernetes/events"

    service:
      telemetry:
        logs:
          level: info
      extensions:
        - health_check
        - file_storage
        - pprof
      pipelines:
        logs/events:
          receivers:
            - raw_k8s_events
          processors:
            - memory_limiter
            - source
            - batch
          exporters:
            - sumologic
kind: ConfigMap
metadata:
  labels:
    app: collection-sumologic-otelcol-events
  name: collection-sumologic-otelcol-events
  namespace: sumologic
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: collection-sumologic-otelcol-events
  name: collection-sumologic-otelcol-events
  namespace: sumologic
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: collection-sumologic-otelcol-events
  serviceName: collection-sumologic-otelcol-events-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/name: collection-sumologic-otelcol-events
    spec:
      containers:
      - args:
        - --config=/etc/otelcol/config.yaml
        env:
        - name: SUMO_ENDPOINT_DEFAULT_EVENT_SOURCE
          valueFrom:
            secretKeyRef:
              key: endpoint-events
              name: sumologic
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: localhost:32000/sumologic-otel-collector-local:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: otelcol
        ports:
        - containerPort: 1777
          name: pprof
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/otelcol
          name: otelcol-config
        - mountPath: /var/lib/storage/otc
          name: buffer
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          chown -R \
            0:0 \
            /var/lib/storage/otc
        image: busybox
        imagePullPolicy: Always
        name: changeowner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/storage/otc
          name: buffer
      restartPolicy: Always
      serviceAccount: collection-sumologic
      serviceAccountName: collection-sumologic
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: collection-sumologic-otelcol-events
        name: otelcol-config
  volumeClaimTemplates:                                                                                                                                                                            
   - apiVersion: v1                                                                                                                                                                                 
     kind: PersistentVolumeClaim                                                                                                                                                                    
     metadata:                                                                                                                                                                                                                                                                                                                                                       
       name: buffer                                                                                                                                                                                 
     spec:                                                                                                                                                                                          
       accessModes:                                                                                                                                                                                 
       - ReadWriteOnce                                                                                                                                                                              
       resources:                                                                                                                                                                                   
         requests:                                                                                                                                                                                  
           storage: 10Gi                                                                                                                                                                            
       volumeMode: Filesystem
