{{- if eq (include "otelevents.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sumologic.metadata.name.events.configmap" . }}
  labels:
    app: {{ template "sumologic.labels.app.events.configmap" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "conf/events/otelcol/config.yaml").AsConfig .) | nindent 2 }}
{{- end }}
